//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestiLog.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Agente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Agente()
        {
            this.AgenteNav = new HashSet<Agente>();
            this.MblNav = new HashSet<Mbl>();
            this.MawbNav = new HashSet<Mawb>();
            this.TarifarioAereo = new HashSet<TarifarioAereo>();
            this.TarifarioFcl = new HashSet<TarifarioFcl>();
            this.TarifarioLcl = new HashSet<TarifarioLcl>();
            this.TarifarioLcl1 = new HashSet<TarifarioLcl>();
        }
    
        public System.Guid Id { get; set; }
        public string Nombre { get; set; }
        public string Nit { get; set; }
        public string Dv { get; set; }
        public string Direccion { get; set; }
        public System.Guid Ciudad { get; set; }
        public System.Guid TipoOficina { get; set; }
        public Nullable<System.Guid> Sucursal { get; set; }
        public System.Guid S_Usuario { get; set; }
        public System.DateTime S_Creacion { get; set; }
        public bool Habilitado { get; set; }
        public Nullable<System.Guid> TipoAgente { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Agente> AgenteNav { get; set; }
        public virtual Agente AgenteNav_ { get; set; }
        public virtual Ciudad CiudadNav { get; set; }
        public virtual TipoOficina TipoOficinaNav { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Mbl> MblNav { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Mawb> MawbNav { get; set; }
        public virtual TipoAgente TipoAgenteNav { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TarifarioAereo> TarifarioAereo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TarifarioFcl> TarifarioFcl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TarifarioLcl> TarifarioLcl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TarifarioLcl> TarifarioLcl1 { get; set; }
    }
}
