//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestiLog.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hawb
    {
        public System.Guid Id { get; set; }
        public System.Guid Mawb { get; set; }
        public string Do { get; set; }
        public string Hbl { get; set; }
        public Nullable<System.Guid> Tipo { get; set; }
        public Nullable<System.Guid> Cliente { get; set; }
        public Nullable<System.Guid> Proveedor { get; set; }
        public Nullable<System.Guid> Notify { get; set; }
        public Nullable<System.Guid> Sucursal { get; set; }
        public Nullable<System.Guid> Incoterm { get; set; }
        public Nullable<System.Guid> AeropuertoOrigen { get; set; }
        public Nullable<System.Guid> AeropuertoDestino { get; set; }
        public Nullable<double> Peso { get; set; }
        public Nullable<double> PesoCargable { get; set; }
        public Nullable<double> DimensionLargo { get; set; }
        public Nullable<double> DimensionAncho { get; set; }
        public Nullable<double> DimensionAlto { get; set; }
        public Nullable<double> Volumen { get; set; }
        public Nullable<System.Guid> Embalaje { get; set; }
        public Nullable<int> Piezas { get; set; }
        public string Mercancia { get; set; }
        public Nullable<int> Imo { get; set; }
        public string Un { get; set; }
        public Nullable<System.DateTime> EntregaDocumentoFecha { get; set; }
        public string EntregaDocumentoNombre { get; set; }
        public Nullable<System.DateTime> ConfirmacionArribo { get; set; }
        public Nullable<System.Guid> Disposicion { get; set; }
        public Nullable<System.Guid> EmisionAwb { get; set; }
        public Nullable<int> RegistroAduanero { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
        public Nullable<System.DateTime> FechaLiberacion { get; set; }
        public string QuienLibera { get; set; }
        public System.Guid S_Usuario { get; set; }
        public System.DateTime S_Creacion { get; set; }
        public bool Habilitado { get; set; }
    
        public virtual Aeropuerto AeropuertoOrigenNav { get; set; }
        public virtual Aeropuerto AeropuertoDestinoNav { get; set; }
        public virtual Cliente ClienteNav { get; set; }
        public virtual Disposicion DisposicionNav { get; set; }
        public virtual Embalaje EmbalajeNav { get; set; }
        public virtual EmisionAwb EmisionAwbNav { get; set; }
        public virtual HawbTipo HawbTipoNav { get; set; }
        public virtual Incoterm IncotermNav { get; set; }
        public virtual Mawb MawbNav { get; set; }
        public virtual Notify NotifyNav { get; set; }
        public virtual Proveedor ProveedorNav { get; set; }
        public virtual Sucursal SucursalNav { get; set; }
    }
}
