//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestiLog.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mawb
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Mawb()
        {
            this.HawbNav = new HashSet<Hawb>();
        }
    
        public System.Guid Id { get; set; }
        public string Do { get; set; }
        public string Master { get; set; }
        public Nullable<System.Guid> Agente { get; set; }
        public Nullable<System.Guid> Aerolinea { get; set; }
        public Nullable<System.Guid> Operativo { get; set; }
        public Nullable<System.Guid> AeropuertoOrigen { get; set; }
        public Nullable<System.Guid> AeropuertoDestino { get; set; }
        public Nullable<System.DateTime> Etd { get; set; }
        public Nullable<System.DateTime> FechaEstimadaArribo { get; set; }
        public bool Conexion { get; set; }
        public Nullable<System.Guid> AerolineaConexion { get; set; }
        public Nullable<System.Guid> AeropuertoConexion { get; set; }
        public Nullable<System.DateTime> FechaConexion { get; set; }
        public string ViajeConexion { get; set; }
        public Nullable<double> Peso { get; set; }
        public Nullable<double> PesoCargable { get; set; }
        public Nullable<double> DimensionLargo { get; set; }
        public Nullable<double> DimensionAncho { get; set; }
        public Nullable<double> DimensionAlto { get; set; }
        public Nullable<double> Volumen { get; set; }
        public Nullable<System.Guid> Embalaje { get; set; }
        public Nullable<int> Piezas { get; set; }
        public string Mercancia { get; set; }
        public Nullable<int> Imo { get; set; }
        public System.Guid S_Usuario { get; set; }
        public System.DateTime S_Creacion { get; set; }
        public bool Habilitado { get; set; }
    
        public virtual Aerolinea AerolineaNav { get; set; }
        public virtual Aerolinea AerolineaConexionNav { get; set; }
        public virtual Aeropuerto AeropuertoOrigenNav { get; set; }
        public virtual Aeropuerto AeropuertoDestinoNav { get; set; }
        public virtual Aeropuerto AeropuertoConexionNav { get; set; }
        public virtual Agente AgenteNav { get; set; }
        public virtual Embalaje EmbalajeNav { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hawb> HawbNav { get; set; }
        public virtual Operativo OperativoNav { get; set; }
    }
}
