//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestiLog.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Naviera
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Naviera()
        {
            this.NavieraNav = new HashSet<Naviera>();
            this.MblNav = new HashSet<Mbl>();
            this.TarifarioFclNav = new HashSet<TarifarioFcl>();
            this.TarifarioLclNav = new HashSet<TarifarioLcl>();
        }
    
        public System.Guid Id { get; set; }
        public string Nombre { get; set; }
        public string Nit { get; set; }
        public string Dv { get; set; }
        public string Direccion { get; set; }
        public System.Guid Ciudad { get; set; }
        public System.Guid TipoOficina { get; set; }
        public Nullable<System.Guid> Sucursal { get; set; }
        public string Representante { get; set; }
        public System.Guid S_Usuario { get; set; }
        public System.DateTime S_Creacion { get; set; }
        public bool Habilitado { get; set; }
        public string Telefono { get; set; }
    
        public virtual Ciudad CiudadNav { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Naviera> NavieraNav { get; set; }
        public virtual Naviera NavieraNav_ { get; set; }
        public virtual TipoOficina TipoOficinaNav { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Mbl> MblNav { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TarifarioFcl> TarifarioFclNav { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TarifarioLcl> TarifarioLclNav { get; set; }
    }
}
