//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestiLog.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TarifarioEscalaItem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TarifarioEscalaItem()
        {
            this.TarifarioAereoItemNav = new HashSet<TarifarioAereoItem>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid TarifarioEscala { get; set; }
        public bool Rango { get; set; }
        public Nullable<int> Desde { get; set; }
        public int Hasta { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TarifarioAereoItem> TarifarioAereoItemNav { get; set; }
        public virtual TarifarioEscala TarifarioEscalaNav { get; set; }
    }
}
