//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestiLog.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TarifarioAereoItem
    {
        public System.Guid Id { get; set; }
        public System.Guid TarifarioAereo { get; set; }
        public System.Guid TarifarioEscalaItem { get; set; }
        public System.Guid Moneda { get; set; }
        public Nullable<double> TarifaNeta { get; set; }
        public Nullable<double> TarifaVenta { get; set; }
        public Nullable<double> TarifaInformada { get; set; }
    
        public virtual Moneda MonedaNav { get; set; }
        public virtual TarifarioAereo TarifarioAereoNav { get; set; }
        public virtual TarifarioEscalaItem TarifarioEscalaItemNav { get; set; }
    }
}
