//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestiLog.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TarifarioViaAerea
    {
        public System.Guid Id { get; set; }
        public System.Guid TarifarioAereo { get; set; }
        public System.Guid Aeropuerto { get; set; }
    
        public virtual TarifarioAereo TarifarioAereoNav { get; set; }
        public virtual Aeropuerto AeropuertoNav { get; set; }
    }
}
