//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestiLog.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TarifarioLcl
    {
        public System.Guid Id { get; set; }
        public int Consecutivo { get; set; }
        public System.Guid Area { get; set; }
        public Nullable<System.Guid> Naviera { get; set; }
        public Nullable<System.Guid> Agente { get; set; }
        public Nullable<System.Guid> Cocargador { get; set; }
        public Nullable<System.Guid> PuertoOrigen { get; set; }
        public Nullable<System.Guid> PuertoDestino { get; set; }
        public Nullable<System.Guid> Frecuencia { get; set; }
        public Nullable<int> TiempoTransito { get; set; }
        public Nullable<System.DateTime> VigenciaDesde { get; set; }
        public Nullable<System.DateTime> VigenciaHasta { get; set; }
        public string Mercancia { get; set; }
        public bool Dg { get; set; }
        public Nullable<System.Guid> Divisa { get; set; }
    
        public virtual Agente AgenteNav { get; set; }
        public virtual Agente CocargadorNav { get; set; }
        public virtual Area AreaNav { get; set; }
        public virtual Frecuencia FrecuenciaNav { get; set; }
        public virtual Moneda DivisaNav { get; set; }
        public virtual Naviera NavieraNav { get; set; }
        public virtual Puerto PuertoOrigenNav { get; set; }
        public virtual Puerto PuertoDestinoNav { get; set; }
    }
}
